### ISSUE TITLE
Make the code look more functional

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#13]
This code modifies a lot of input arguments in place.  It would be nice for it to return them as well (or instead of modifying them in place).

**Comment by speleo3** [comment]
My favorite API would be top-level `pdbx.load`, `pdbx.loads`, `pdbx.dump`, `pdbx.dumps` functions, inspired by `json` and `pickle` APIs.

`pdbx.loads` could be implemented exactly like the [read_cifstr](https://github.com/Electrostatics/mmcif_pdbx/blob/ff6e834d9a74b3f3de0c9cd05fe109af94646c05/tests/reader_test.py#L47) test helper function.

Thoughts?

**Comment by sobolevnrm** [comment]
I like it.  @intendo - I wonder if we should update the PDB2PQR PDB interface to match?

**Comment by intendo** [comment]
@sobolevnrm, I added comments about this in PR #29 
Whatever we do in pdbx I think would be go to do in PDB2PQR interface to be consistent.

**Comment by sobolevnrm** [comment]
> @sobolevnrm, I added comments about this in PR #29
> Whatever we do in pdbx I think would be go to do in PDB2PQR interface to be consistent.

I agree with the comments of @speleo3 in PR #29 and agree with your suggestion that we use similar method names for PDB input/output in PDB2PQR.

**Comment by intendo** [comment]
@sobolevnrm can we close out this issue?

**Comment by sobolevnrm** [comment]
No.  I was actually referring to more of the code (as a whole) follow more patterns that look like functional programming.

**Comment by sobolevnrm** [comment]
> No. I was actually referring to more of the code (as a whole) follow more patterns that look like functional programming.

But, honestly, it's *very* low priority... maybe we should just close.
