### ISSUE TITLE
Github actions pushing coverage results to Jensen group

### ISSUE THREAD

**Issue by intendo** [Electrostatics/mmcif_pdbx#16]
**Describe the bug**
In the .github/workflows/python-package.yml file there are references to:
    - name: Upload coverage to https://codecov.io/gh/jensengroup/propka
      run: bash <(curl -s https://codecov.io/bash

**Expected behavior**
There should probably be a codecov.io/gh/Electrostatics/mmcif_pdbx site

**Comment by intendo** [comment]
Not a bug, just a typo in the name.

The coverage is correctly sent to https://codecov.io/gh/Electrostatics/mmcif_pdbx

**Comment by intendo** [comment]
Fixed with PR #17

**Comment by sobolevnrm** [comment]
Thanks -- cut & paste... :(
