### ISSUE TITLE
Refactor usage of StopIteration in pdbx.reader

### ISSUE THREAD

**Issue by speleo3** [Electrostatics/mmcif_pdbx#22]
`pdbx.reader` follows a pre-[PEP 479](https://www.python.org/dev/peps/pep-0479/) pattern of `StopIteration` usage with a `RuntimeError` band-aid. This should be refactored.

@sobolevnrm I'd be happy to send a pull request, unless this code is already being worked on.

**Comment by intendo** [comment]
@speleo3 I saw that as well but didn't have a good strategy for refactoring. If you have time, feel free to send a PR.
