### ISSUE TITLE
Flatten Namespace

### ISSUE THREAD

**Issue by intendo** [Electrostatics/mmcif_pdbx#32]
Looking again at json and pickle: 

They put everything API relevant in the top-level module namespace. E.g. json.JSONDecoder instead of json.decoder.JSONDecoder (actual implementation). "Flat is better than nested" (The Zen of Python) so to speak.

**Comment by speleo3** [comment]
To elaborate on this, I suggest to put the following items in the top-level `pdbx` namespace:
- `PdbxSyntaxError`
- `PdbxError`
- `DataContainer`
- `DataCategory`

I see currently no reason to put other classes there, e.g. I see `PdbxReader` and `PdbxWriter` as implementation details as their functionality is fully covered by `pdbx.load` and `pdbx.dump`.
