### ISSUE TITLE
Release new version of mmcif-pdbx

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#43]
Actually, something is wrong with the PyPI version.  I think we just need to release a new, clean version.

_Originally posted by @sobolevnrm in https://github.com/Electrostatics/mmcif_pdbx/issues/41#issuecomment-744116624_

**Comment by sobolevnrm** [comment]
@orbeckst and @speleo3 -- I'd like to release a new version of the package for two reasons:

* Something is messed up with the current PyPI package
* 1.1.2 should have been a MAJOR or MINOR release since it changed the way packages were loaded and used.

Therefore, I think we should release 2.0.0.  Do you agree?  If so, I need to do the following:

- [ ] Wait for your review of #44 
- [ ] Figure out how to use versioneer to tell it to update the version to 2.0.0 (or is this just from the tag in the repo?)
- [ ] Release the package to PyPI.
- [ ] Ask @tsenapathi for help with conda package release.

Does this sound OK to you?

**Comment by intendo** [comment]
According to https://jacobtomlinson.dev/posts/2020/versioning-and-formatting-your-python-code/, versioneer will get the version number from the Github tag:

```
git tag 2.0.0
```

**Comment by sobolevnrm** [comment]
https://github.com/Electrostatics/mmcif_pdbx/releases/tag/v2.0.0
