### ISSUE TITLE
Convert to/from PDB format?

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#46]
I'd like to be able to have PDB2PQR deal with only one kind of data structure for input files.  To that end, I wonder what @orbeckst and @speleo3 would think about moving the PDB input/output code into this package so that PDB files could easily be converted to/from CIF?

**Comment by intendo** [comment]
That would be great and would make it easier to support PDB files in APBS and PDB2PQR.

**Comment by speleo3** [comment]
Right now, this package is all (and only) about the container data structure, not about the semantics of molecules. Adding PDB input/output would change that scope. I personally like to see the two separated, but I also understand if you care more about molecules than data containers and don't want to introduce yet another package.

**Comment by sobolevnrm** [comment]
@speleo3 -- that's a good point.  Perhaps I'll create another package with this one as a dependency.  The other package would allow us more flexibility with APBS/PDB2PQR while keeping this one clean.  thanks!
