### ISSUE TITLE
Make reader more functional

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#49]
https://github.com/Electrostatics/mmcif_pdbx/blob/7de84811e8863b38555b371d1f824473cbb30cf4/pdbx/reader.py#L50

I'd like to make `pdbx.PdbxReader.read` more functional by returning the container list in addition to modifying it in place.

@speleo3 and @orbeckst -- what do you think?

**Comment by speleo3** [comment]
I agree that a return value is a nicer API than an out-variable. Another option would be a generator which yields containers. Do you have a use case for using `PdbxReader.read()` directly instead of `pdbx.load()`?

**Comment by sobolevnrm** [comment]
I wasn't using `pdbx.load` because I forgot it existed. 😂
